title=Mitgliederversammlung des Fördervereins
date=2019-09-23
type=post
tags=Förderverein
status=published
~~~~~~
An alle Mitglieder und Interessierte

= Einladung zur Mitgliederversammlung des Fördervereins

Liebe Eltern, sehr geehrte Mitglieder des Fördervereins,

kurz vor den Ferien möchte ich Sie noch gerne zur Mitgliederversammlung des
Fördervereins am Montag, den 23.09.2019 um 19:30 Uhr im Aufenthaltsraum der UvDSchule
(Erdgeschoss Neubau) einladen.

Tagesordnungspunkte sind:

1. Begrüßung und Feststellung der Beschlussfähigkeit
2. Neuwahlen von
   a) 1. Vorsitzende/r
   b) 2. Vorsitzende/r
   c) Kassenprüfer/in
3. Planung für Café auf der Aus- und Weiterbildungsbörse am 12. Oktober
4. Planungen und weitere Ideen für 2019/20
5. Verschiedenes

Frau Herzog möchte nach 10 Jahren aktiver Arbeit für den Förderverein ihr Amt als 2.
Vorsitzende aufgeben. Wir sind daher auf der Suche nach einer Nachfolgerin oder
eines Nachfolgers. Ebenfalls neu besetzt werden muss das Amt des zweiten
Kassenprüfers bzw. Kassenprüferin. Wenn Sie sich vorstellen können, sich aktiv beim
Förderverein zu beteiligen, dann melden Sie sich doch bitte – denn ohne die Besetzung
dieser Ämter kann der Förderverein nicht weitergeführt werden.

Weitere Punkte zur Tagesordnung nehmen wir gerne vorzugsweise per E-Mail
(uvdfoerderverein@web.de) entgegen. Unter Punkt „Verschiedenes“ ist aber auch noch
Platz für spontane Beiträge.

Wir freuen uns über eine rege Teilnahme und Ihre Ideen!

Mit freundlichen Grüßen,

Bernhard Haumacher (1. Vorsitzender) +
Sabine Herzog (2. Vorsitzende) +
Amelie Thamm (Kassenwartin) +