title=Neue AG-Termine
date=2016-09-21
type=post
tags=AG
status=published
~~~~~~
Liebe Kinder, liebe Eltern, 

nächste Woche starten unsere AG-Angebote wieder. Bei den Sport- und Musikangeboten dürfen alle Kinder, die letztes Jahr eine AG besucht haben wieder in diese AG gehen.

Bei der Forscher-AG geht das leider nicht, da auch andere Kinder die Chance haben sollen, die Forscher-AG zu besuchen. Anmelden können sich diese Kinder aber trotzdem. Falls sich nicht genug neue Kinder anmelden, können die übrigen Plätze ausgelost werden.

Die Zeiten der Musikangebote können sich noch ändern, falls es so viele Kinder gibt, dass wir mehrere Gruppen einrichten müssen. Geben Sie bitte deshalb das Zeitfenster an, innerhalb dessen die Kinder Zeit haben.

Bitte beachten Sie, liebe Eltern, dass die Anmeldung zu einer AG für ein Schuljahr verbindlich ist. Die Kinder müssen die AG zu der sie angemeldet sind dann genauso besuchen, wie den Regelunterricht, bzw. müssen entschuldigt werden, wenn sie krank sein sollten.

Die Termine der AGs sind wie folgt:

=== Schulchor
Mittwoch 6. Stunde 12:05 - 12:50 Uhr (Klassen 2 bis 4)

=== Handball
Montag 14:30 - 15:30 Uhr (Klassen 1 und 2)

Montag 15:30 - 16:30 Uhr (Klassen 3 und 4)

=== Forscher-AG
Dienstag  14:00 - 15:30 Uhr (nur Klassen 3 und 4 - max. 12 Kinder)

=== Basketball
Mittwoch 15:30 - 17:00 Uhr

=== Musik und Tanz
Donnerstag 14:30 - 16:00 Uhr (Tanz)

Donnerstag 15:00 - 16:00 Uhr (Instrumente Flöte, Querflöte, Trompete, Saxofon, Trommel)
