title=UvD wird Grundschule
date=2015-08-01
type=post
tags=aktuelles
status=published
~~~~~~
== "`... dass nichts bleibt, dass nichts bleibt, wie es war.`" (https://en.wikipedia.org/wiki/Hannes_Wader[Hannes Wader])

Die UvD muss sich verändern. Nachdem in den vergangenen 100 Jahren die Schüler und Schülerinnen in diesem Schulhaus bis zum Schulabschluss geführt wurden, endet diese Phase nun im Juli 2015.

Ab dem neuen Schuljahr wird die UvD nur noch Grundschule sein.

Die noch verbliebenen Werkrealschüler gehören dann zur Schillerschule. Sie werden aber ihre restlichen Schuljahre im UvD-Schulhaus unterrichtet werden.

Wegen Platzmangels in der Schillerschule werden weitere Klassen der Schillerschule in das UvD-Schulhaus ausgelagert, so dass es trotz der Veränderung weiterhin große Schüler als "`Gäste`" im Haus geben wird.

Auch die Mehrzahl der LehrerInnen der Werkrealschule werden mit ihren Schülern an die Schillerschule wechseln. Schulleitung, GrundschullehrerInnen, Sekretariat, Schulsozialarbeit und der Hausmeister bleiben an der UvD.
